famous_persons = [
    "Albert Einstein",
    "Isaac Newton",
    "Leonardo da Vinci",
    "William Shakespeare",
    "Charles Darwin",
    "Galileo Galilei",
    "Aristotle",
    "Plato",
    "Socrates",
    "Alexander the Great",
    "Julius Caesar",
    "Napoleon Bonaparte",
    "Abraham Lincoln",
    "George Washington",
    "Winston Churchill",
    "Mahatma Gandhi",
    "Nelson Mandela",
    "Martin Luther King Jr.",
    "Mother Teresa",
    "Marie Curie",
    "Thomas Edison",
    "Nikola Tesla",
    "Louis Pasteur",
    "Sigmund Freud",
    "Mozart",
    "Beethoven",
    "Johann Sebastian Bach",
    "Franz Schubert",
    "Claude Monet",
    "Vincent van Gogh",
    "Pablo Picasso",
    "Rembrandt",
    "Salvador Dali",
    "Andy Warhol",
    "Elvis Presley",
    "Michael Jackson",
    "The Beatles",
    "Madonna",
    "Beyoncé",
    "John Lennon",
    "Freddie Mercury",
    "Bob Marley",
    "James Dean",
    "Marilyn Monroe",
    "Audrey Hepburn",
    "Elizabeth Taylor",
    "Charlie Chaplin",
    "Alfred Hitchcock",
    "Steven Spielberg",
    "Stanley Kubrick",
    "Quentin Tarantino",
    "Robert De Niro",
    "Meryl Streep",
    "Tom Hanks",
    "Leonardo DiCaprio",
    "Brad Pitt",
    "Angelina Jolie",
    "Oprah Winfrey",
    "Bill Gates",
    "Steve Jobs",
    "Mark Zuckerberg",
    "Jeff Bezos",
    "Elon Musk",
    "Warren Buffett",
    "Barack Obama",
    "Donald Trump",
    "Vladimir Putin",
    "Angela Merkel",
    "Franklin D. Roosevelt",
    "Ronald Reagan",
    "Margaret Thatcher",
    "Queen Elizabeth II",
    "Diana, Princess of Wales",
    "Pope Francis",
    "Dalai Lama",
    "Stephen Hawking",
    "Richard Feynman",
    "Jane Goodall",
    "Rachel Carson",
    "Malala Yousafzai",
    "Greta Thunberg",
    "Serena Williams",
    "Michael Jordan",
    "Muhammad Ali",
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Roger Federer",
    "Usain Bolt",
    "Tiger Woods",
    "Pele",
    "Diego Maradona",
    "Ayrton Senna",
    "Michael Schumacher",
    "Lewis Hamilton",
    "Neil Armstrong",
    "Yuri Gagarin",
    "Buzz Aldrin",
    "Sally Ride",
    "Mae Jemison",
    "Bob Dylan"
]
print(len(famous_persons))